### ISSUE TITLE
Issue in Paths

### ISSUE THREAD

**Issue by Mohamed-E-Fayed** [duguyue100/wmt-en2wubi#1]
I did:
1. clone, 
2. edit wit-en2wubi/en2wubi/Makefile to use python3 command instead of python. I'm on Ubuntu 20.04 LTS, and python 3.8.5)
3. run $pip3 install -r wmt-en2wubi/en2wubi/requirements.txt
4. write the following lines to file.sh and run the script :
```
cd wmt-en2wubi/en2wubi
make convert-cn2wb IN=~/data/zh-ar/train.zh-ar.zh OUT=~/data/zh-ar/train.zh.wb

```

I get this output (including error)

PYTHONPATH=":/home/mohamed/scripts/convtransformer/convtransformer/wmt-en2wubi/en2wubi" python3 ./en2wubi/scripts/convert_text.py --input-doc ~/data/zh-ar/train.zh-ar.zh --output-doc ~/data/zh-ar/train.zh.wb --convert-type ch2wb
Traceback (most recent call last):
  File "./en2wubi/scripts/convert_text.py", line 10, in <module>
    import en2wubi as e2w
  File "/home/mohamed/scripts/convtransformer/convtransformer/wmt-en2wubi/en2wubi/en2wubi/__init__.py", line 11, in <module>
    E2W_PATH = os.environ["EN2WUBI_PATH"]
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'EN2WUBI_PATH'
make: *** [Makefile:21: convert-cn2wb] Error 1

When I try:
```
python3 wmt-en2wubi/en2wubi/en2wubi/scripts/convert_text.py --input-doc /path/to/input/file.zh --output-doc /path/to/output/file.zh.wb --convert-type ch2wb 
```

I get:
Traceback (most recent call last):
  File "wmt-en2wubi/en2wubi/en2wubi/scripts/convert_text.py", line 10, in <module>
    import en2wubi as e2w
ModuleNotFoundError: No module named 'en2wubi'

What am I doing wrong?!

Thank you so much.

**Comment by duguyue100** [comment]
Hi @Mohamed-E-Fayed, sorry for the late reply.

The `KeyError` says all, there is a missing environment variable `EN2WUBI_PATH`. In the instruction, I wrote:

```
export EN2WUBI_PATH=$HOME/.en2wubi
```
You can put the above line in your `.bashrc` as well.

and please run `make setup` before running the convert text script.

Yuhuang.

**Comment by Mohamed-E-Fayed** [comment]
Hi @duguyue100 ,
Thank you so much for the reply, and sorry for my late reply as ell.

It worked thank you so much for your help. 😊
